config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'commands#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
  resources :commands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/command.rb
class Command < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :language, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :commands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @pagy,@commands = pagy(current_user.commands.order(:id), items: 10)
  end
  
  def show
  end

  def new
    @command = Command.new
  end

  def create
    @command = current_user.commands.build(command_params)
    
    if @command.save
      flash[:success] = 'Command が正常に追加されました'
      redirect_to @command
    else
      flash.now[:danger] = 'Command が追加されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @command.update(command_params)
      flash[:success] = 'Command は正常に更新されました'
      redirect_to @command
    else
      flash.now[:danger] = 'Command は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @command.destroy

    flash[:success] = 'Command は正常に削除されました'
    redirect_to commands_url
  end
  
  private
  
  def command_params
    params.require(:command).permit(:content, :name, :language)
  end
  
  def correct_user
    @command = current_user.commands.find_by(id: params[:id])
    unless @command
      redirect_to root_url
    end
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commands/_form.html.erb
<%= form_with(model: command) do |f| %>
  <% if command.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% command.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= f.label :name, 'コマンド' %>
    <%= f.text_field :name, class: 'form-control'  %> 
  </div>
  
  <div class="mb-3">
    <%= f.label :language, '言語' %>
    <%= f.text_field :language, class: 'form-control'  %>
  </div>
  
  <div class="mb-3">
    <%= f.label :content, '内容' %>
    <%= f.text_area :content, class: 'form-control'  %>
  </div>
  
  <%= f.submit '追加', class: 'btn btn-primary' %>
<% end %>

app/views/commands/edit.html.erb
<h1>id: <%= @command.id %> のコマンド編集ページ</h1>

<%= render 'form', command: @command %>

app/views/commands/index.html.erb
<h1>コマンド一覧</h1>

<% if @commands.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>コマンド</th>
        <th>言語</th>
        <th>内容</th>
      </tr>
    </thead>
    <tbody>
      <% @commands.each do |command| %>
        <tr>
          <td><%= link_to command.id, command %></td>
          <td><%= command.name %></td>
          <td><%= command.language %></td>
          <td><%= command.content %></td>
      <% end %>
    </tbody>
  </table>
  <div>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>  
<%= link_to '新規コマンドの追加', new_command_path, class: "btn btn-primary" %>

app/views/commands/new.html.erb
<h1>コマンド新規作成ページ</h1>

<%= render 'form', command: @command %>

app/views/commands/show.html.erb
<h1>id: <%= @command.id %> のコマンド詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @command.id %></td>
  </tr>
  <tr>
    <th>コマンド</th>
    <td><%= @command.name %></td>
  </tr>
  <tr>
    <th>言語</th>
    <td><%= @command.language %></td>
  </tr>
  <tr>
    <th>内容</th>
    <td><%= @command.content %></td>
  </tr>
</table>

<%= link_to 'このコマンドを編集する', edit_command_path(@command), class: 'btn btn-light' %>
<%= link_to 'このコマンドを削除する', @command, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Commandlist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- メニュー項目 -->
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <div class="btn-group">
            <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commandlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>